reviewers:
  defaults:
    - team:FullAccess
    - admins

groups:
  admins:
    - btuttle-fnba
  readme_reviewers:
    - turtle-fnba

per_author:
  readme_editors:
    - readme_reviewers

files:
  '**':
    - btuttle-fnba
    - admins
  'README.md':
    - team:readme_editors
    - readme_reviewers
    
options:
  ignore_draft: true
  enable_group_assignment: false
  number_of_reviewers: 1
  last_files_match_only: true
