reviewers:
  defaults:
    - team:FullAccess
    - admins

groups:
  admins:
    - btuttle-fnba

# Do 'Per Author' when more accounts are available

files:
  '**':
    - btuttle-fnba
    - admins
  'README.md':
    - team:readme_editors

options:
  ignore_draft: true 
  enable_group_assignment: false
  number_of_reviewers: 1
  last_files_match_only: true
