name: Auto Request Review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened]
    branches: [master]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml # Config file location override
          use_local: true
